stages:
  - test

unit-test:
  stage: test
  image: python:3.12
  script:
      - pip install -r requirements.txt
      - pytest --cov-report=html --cov=src
  artifacts:
    paths:
        - coverage
    expire_in: 30days